db:
  image: postgres
  ports:
    - 5432
  environment:
    - POSTGRES_DB=yeezy

nginx-proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock

web:
  build: .
  ports:
    - '8080:8080'
  command: bash -c "sleep 5; npm start"
  links:
    - db
  environment:
    - DB_HOST=db
    - DB_PORT=5432
    - DB_NAME=yeezy
    - DB_USERNAME=postgres
    - DB_PASSWORD=postgres
    - VIRTUAL_HOST=yeezyme.com
    - VIRTUAL_PORT=8080
